language: node_js
node_js:
  - 0.12.7
before_install:
  - rvm install 2.2.1
install:
  - bundle install
before_script:
  - npm install -g bower gulp
  - npm install
  - bower install
script: ./_scripts/build.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: ./_scripts/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./_scripts/deploy.sh
    on:
      branch: master
      tags: true
notifications:
pushover:
  api_key: $pushover_app
  users:
    - $pushover_user
  template: "%{repository} (%{commit}) : %{message} %{foo} - Build details: %{build_url}"
