# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nicholasjay.com
email: djparadyme@gmail.com
description: Nick's home
baseurl: ""
url: "http://localhost"

social:
  -
    name: twitter
    username: djparadyme
    url: https://twitter.com/djparadyme
    icon: icon
  -
    name: github
    username: nicholasjay
    url: https://github.com/nickroberts
    icon: icon

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown

# Includes
include: ["_pages"]

# Excludes
exclude: [
  "bower_components",
  "node_modules",
  "bower.json",
  "gulp.config.js",
  "gulpfile.js",
  "package.json",
  "README.md",
  "js/app.js",
  "css/app.css",
  "vendor",
  "Gemfile",
  "Gemfile.lock",
]
